# Numpy
Numrical Python


pic = Packege manager is to download certain packege of python

pip install packege name

book: learning pandas (from FB AI page)

In [4]:
import numpy as np

In [6]:

my_arr=np.arange(100000)

In [8]:
my_arr

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [13]:
my_list=list(range(10))

In [15]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
type(my_arr)

numpy.ndarray

In [21]:
%time for _ in range(10): my_arr2=[x*2for x in my_list]

Wall time: 0 ns


In [23]:
%time for _ in range(10): my_arr2 =my_arr*2

Wall time: 1.97 ms


In [27]:
data=np.random.randn(20,30)

In [28]:
data

array([[-1.31894630e+00,  4.32566751e-01,  8.10988907e-02,
         7.68160948e-01, -6.16053895e-01, -2.11738511e+00,
        -1.10321547e+00, -1.29955686e+00, -2.19902736e-01,
         2.62950626e-01,  3.69127750e-01, -1.99584690e+00,
        -4.79073815e-01,  8.97941039e-01, -6.21032713e-01,
        -1.75537390e-01, -6.92111094e-02, -3.69255004e-02,
         4.06919169e-02,  1.31011372e-01, -1.35710185e+00,
         1.73246476e+00,  4.50906345e-01, -6.52522390e-01,
         3.72569425e-01,  6.28253802e-01,  3.68741889e-01,
        -1.14444733e+00, -7.31898274e-01, -4.40321393e-01],
       [-1.77903186e-01, -1.85163811e-01, -1.72981477e+00,
        -1.42323211e+00, -2.18157258e-01, -1.61941454e+00,
        -4.53495285e-01, -3.91486763e-01,  7.33286658e-01,
        -2.68360943e-01,  1.57320476e+00, -3.90785330e-01,
        -8.22953437e-01, -1.89936051e-01, -2.71821289e-01,
        -9.85752322e-01,  2.40460120e-01, -7.29340259e-01,
        -1.49712606e+00, -5.84584565e-01, -1.27701136e+

In [30]:
data=np.random.randn(2,3)

In [32]:
data

array([[-0.32248549, -0.44138762,  0.54299331],
       [ 1.50659824,  0.19484339, -1.06429506]])

In [33]:
a=[1,2,3,4,5,6,7]

In [37]:
c=[1,2,3,4,5,6,7],[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]
    

NameError: name 'c' is not defined

In [38]:
a=[]
for b in c:
    a.append(b*10)

NameError: name 'c' is not defined

In [40]:
k=[]
for i in c:
    for j in i:
        k.append

NameError: name 'c' is not defined

In [43]:
c=np.randam.randan(3,3)

AttributeError: module 'numpy' has no attribute 'randam'

In [45]:
#numpy performs vertorized performance 

In [47]:
my_arr.dtype

dtype('int32')

In [51]:
arr=np.arange(64).reshspr(8,8)
arr

AttributeError: 'numpy.ndarray' object has no attribute 'reshspr'

In [52]:
z=np.array(10)

In [54]:
z

array(10)

In [58]:
z=np.arange(10)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
z.ndim

1

In [63]:
z=np.array([[[10]]])

In [65]:
z.ndim

3

In [66]:
arr3d=arr.reshape(4,4,4)

In [69]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [71]:
arr3d=arr.reshape(4,8,2)
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31]],

       [[32, 33],
        [34, 35],
        [36, 37],
        [38, 39],
        [40, 41],
        [42, 43],
        [44, 45],
        [46, 47]],

       [[48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59],
        [60, 61],
        [62, 63]]])

In [75]:
mat=np.ones((4,5))

In [78]:
mat

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [80]:
mat=np.ones((4,5))*10
mat

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [85]:
np.full(((4,5)),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [87]:
np.eye(6,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
a=np.arr