# numpy array bassic indexing and slicing

In [1]:
import numpy as np
arr2d=np.arange(25).reshape(5,5)

In [2]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [3]:
import numpy as np
arr3d=np.arange(64).reshape(2,8,4)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [4]:
arr3d[1,3,2]

46

In [5]:
arr3d[1][3][2]

46

In [6]:
arr3d=np.arange(64).reshape(4,2,8)

In [7]:
arr3d

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]]])

In [8]:
mat=np.ones((4,5))


In [9]:
mat

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
arr1d=np.arange(20)
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
sliced=arr1d[3:7]
sliced

array([3, 4, 5, 6])

In [12]:
import numpy as np
arr2d=np.arange(25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
arr2d[1:4,1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [14]:
arr2d[1:4,0]

array([ 5, 10, 15])

In [15]:
arr2d[3:4,1:4]

array([[16, 17, 18]])

In [16]:
arr2d[0:5,4:5]

array([[ 4],
       [ 9],
       [14],
       [19],
       [24]])

In [17]:
arr2d[0:,4]

array([ 4,  9, 14, 19, 24])

In [18]:
arr2d[0,2:4]

array([2, 3])

In [19]:
arr2d[0:,4:]

array([[ 4],
       [ 9],
       [14],
       [19],
       [24]])

In [20]:
import numpy as np
arr2d=np.arange(16).reshape(4,4)
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
arr2d[0:4,1:1]

array([], shape=(4, 0), dtype=int32)

In [22]:
arr1d=np.arange(20)
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
arr1d.shape

(20,)

In [24]:
a=np.array(arr1d).reshape(1,20)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [25]:
a.shape

(1, 20)

In [26]:
import numpy as np
arr2d=np.arange(16).reshape(4,4)
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
arr2d[1:2,2:4]

array([[6, 7]])

In [28]:
arr2d[2:,1:]

array([[ 9, 10, 11],
       [13, 14, 15]])

In [29]:
arr2d[0:1,0:2]

array([[0, 1]])

In [30]:
arr2d[1:2,1:2]

array([[5]])

# boolean indexing

In [31]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])


In [32]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [33]:
mydata=np.arange(20).reshape(5,4)
mydata

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [34]:
mydata[[4,2,0]]

array([[16, 17, 18, 19],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

In [35]:
mydata=[[True,False,True,False,True]]

In [36]:
newdata=np.arange(100).reshape(10,10)
newdata

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [37]:
newdata>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [38]:
newdata[newdata>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [39]:
newdata[(newdata>50)]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [40]:
newdata[(newdata>50) & (newdata==60)]

array([60])

In [41]:
newdata%2!=0 

array([[False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
         True]])

In [42]:
newdata[newdata%2!=0 ]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [43]:
data=np.array([2,5,3,8,9,10,12,20,0,1,23,67]).reshape(4,3)

In [44]:
data[(data<5)&(data%2==0)]

array([2, 0])

In [45]:
data=np.array([2,5,3,8,9,10,12,20,0,1,23,67]).reshape(4,3)
print(data)

[[ 2  5  3]
 [ 8  9 10]
 [12 20  0]
 [ 1 23 67]]


In [46]:
data[(data<5)&(data%2==0)]

array([2, 0])